# log4cplus.rootLogger=DEBUG, STDOUT, R3

log4cplus.logger.LaserNavNode=DEBUG, STDOUT, R3
log4cplus.logger.rosTopic=INHERITED, STDOUT, R3
log4cplus.logger.NavPos=DEBUG, R4
log4cplus.logger.RotatePos=DEBUG, R5
log4cplus.logger.LaserNavRefactored=DEBUG, STDOUT, R6

log4cplus.appender.STDOUT=log4cplus::ConsoleAppender
log4cplus.appender.STDOUT.layout=log4cplus::PatternLayout
# %D{xxx}   输出时间戳
# [%t]      输出线程号
# [%-5p]    输出日志级别
# [%c{2}]   输出日志模块名
# [%l]      输出文件所在的文件名称和行号
# %m        输出原始信息
# %n        输出换行符
log4cplus.appender.STDOUT.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S,%Q} [%T] [%-5p] [%c{2}] [%b:%L] %m %n

log4cplus.appender.R3=log4cplus::AsyncAppender
log4cplus.appender.R3.QueueLimit=10000
log4cplus.appender.R3.Appender=log4cplus::RollingFileAppender
# MONTHLY 按月；WEEKLY 按周；DAILY 按天；TWICE_DAILY 按两天；HOURLY 按小时；MINUTELY 按分钟
log4cplus.appender.R3.Appender.Schedule=DAILY
log4cplus.appender.R3.Appender.DatePattern=%Y-%m-%d-%H
log4cplus.appender.R3.Appender.File=${AGV_HOME}/log/laser_navigation.log
log4cplus.appender.R3.Appender.ImmediateFlush=true
log4cplus.appender.R3.Appender.MaxFileSize=10MB  
log4cplus.appender.R3.Appender.MaxBackupIndex=10
log4cplus.appender.R3.Appender.Append=true
log4cplus.appender.R3.Appender.layout=log4cplus::PatternLayout  
log4cplus.appender.R3.Appender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S,%Q} [%T] [%-5p] [%c{2}] [%b:%L] %m %n

log4cplus.appender.R4=log4cplus::AsyncAppender
log4cplus.appender.R4.QueueLimit=10000
log4cplus.appender.R4.Appender=log4cplus::RollingFileAppender
# MONTHLY 按月；WEEKLY 按周；DAILY 按天；TWICE_DAILY 按两天；HOURLY 按小时；MINUTELY 按分钟
log4cplus.appender.R4.Appender.Schedule=DAILY
log4cplus.appender.R4.Appender.DatePattern=%Y-%m-%d-%H
log4cplus.appender.R4.Appender.File=${AGV_HOME}/log/LaserPosition.txt
log4cplus.appender.R4.Appender.ImmediateFlush=true
log4cplus.appender.R4.Appender.MaxFileSize=10MB  
log4cplus.appender.R4.Appender.MaxBackupIndex=5
log4cplus.appender.R4.Appender.Append=true
log4cplus.appender.R4.Appender.layout=log4cplus::PatternLayout  
log4cplus.appender.R4.Appender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S,%Q} %m

log4cplus.appender.R5=log4cplus::AsyncAppender
log4cplus.appender.R5.QueueLimit=10000
log4cplus.appender.R5.Appender=log4cplus::RollingFileAppender
# MONTHLY 按月；WEEKLY 按周；DAILY 按天；TWICE_DAILY 按两天；HOURLY 按小时；MINUTELY 按分钟
log4cplus.appender.R5.Appender.Schedule=DAILY
log4cplus.appender.R5.Appender.DatePattern=%Y-%m-%d-%H
log4cplus.appender.R5.Appender.File=${AGV_HOME}/log/RotatePosition.txt
log4cplus.appender.R5.Appender.ImmediateFlush=true
log4cplus.appender.R5.Appender.MaxFileSize=10MB  
log4cplus.appender.R5.Appender.MaxBackupIndex=5
log4cplus.appender.R5.Appender.Append=true
log4cplus.appender.R5.Appender.layout=log4cplus::PatternLayout  
log4cplus.appender.R5.Appender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S,%Q} %m

log4cplus.appender.R6=log4cplus::AsyncAppender
log4cplus.appender.R6.QueueLimit=10000
log4cplus.appender.R6.Appender=log4cplus::RollingFileAppender
# MONTHLY 按月；WEEKLY 按周；DAILY 按天；TWICE_DAILY 按两天；HOURLY 按小时；MINUTELY 按分钟
log4cplus.appender.R6.Appender.Schedule=DAILY
log4cplus.appender.R6.Appender.DatePattern=%Y-%m-%d-%H
log4cplus.appender.R6.Appender.File=${AGV_HOME}/log/laser_navigation.log
log4cplus.appender.R6.Appender.ImmediateFlush=true
log4cplus.appender.R6.Appender.MaxFileSize=10MB  
log4cplus.appender.R6.Appender.MaxBackupIndex=10
log4cplus.appender.R6.Appender.Append=true
log4cplus.appender.R6.Appender.layout=log4cplus::PatternLayout  
log4cplus.appender.R6.Appender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S,%Q} [%T] [%-5p] [%c{2}] [%b:%L] %m %n
